---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enzol.
--- DateTime: 21/10/2022 18:33
---

fx_version 'cerulean'
game 'gta5'

client_script {
    'build/js/client/*.js',
}

server_script {
    'build/js/server/*.js',
}

ui_page "http://localhost:5173/"

files {
    "web/dist/index.html",
    "web/dist/assets/**",
}